services:

  backend:
    build:
      context: ./backend
    container_name: rag-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: rag-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
   
  postgres:
    image: pgvector/pgvector:pg17
    container_name: rag-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama/init-ollama.sh:/init-ollama.sh
    entrypoint: ["/bin/sh", "/init-ollama.sh"]
    restart: unless-stopped

volumes:
  postgres-data:
  ollama-data: